### ISSUE TITLE
Update to node 8.6.0?

### ISSUE THREAD

**Issue by ncthbrt** [daveamit/node-apline-grpc#1]
Hi there. I was wondering if it would be possible to bump the node version of this container to v8.6.0

**Comment by daveamit** [comment]
Sure. Sorry for delayed response, have been busy.

**Comment by daveamit** [comment]
Updated images available at:
daveamit/node-alpine-grpc:latest (Node version: v9.0.0)
daveamit/node-alpine-grpc:v9.0.0 (Node version: v9.0.0)
daveamit/node-alpine-grpc:v8.9.0 (Node version: v8.9.0)

**Comment by ncthbrt** [comment]
Awesome. Thanks :)
